### ISSUE TITLE
Consider changing to SASS

### ISSUE THREAD

**Issue by lapanti** [lapanti/ts-react-boilerplate#10]
The interest in Less has been in a steady decline since 2015, whereas the interest in SASS has been steadily increasing. This leads to most major CSS-frameworks and tools having SASS-implementations, but no LESS implementation.

Also https://github.com/sass/node-sass removes the need to having ruby installed.

Comments @olliahonen ?

**Comment by olliahonen** [comment]
Node-sass is fine as long as Ruby isn't involved :)

**Comment by lapanti** [comment]
Good good :) (ruby shouldn't be involved), there's already a pull request (which will probably have merge conflicts soon)
