### ISSUE TITLE
Document the application structure

### ISSUE THREAD

**Issue by lapanti** [lapanti/ts-react-boilerplate#2]
Especially the purpose of the application structure and the point of different types of solutions in the app

**Comment by lapanti** [comment]
Another thought: create a gitbook that runs through the application structure, by guiding a beginner in building their own version, all the while linking to relevant documentation etc. Thoughts @olliahonen ?

**Comment by olliahonen** [comment]
Gitbook: It's a lot of work but would be of tremendous value if done properly

**Comment by lapanti** [comment]
Luckily I have nothing but time (*not*)
